local o = vim.o

o.encoding = 'utf-8'
o.lazyredraw = true
o.showcmd = true
o.number = true
o.relativenumber = true
o.smarttab = true
o.expandtab = true
o.softtabstop = 4
o.tabstop = 4
o.shiftwidth = 4
o.cursorline = true
o.cursorcolumn = true
o.showmatch = true
o.hlsearch = true
o.ignorecase = true
o.incsearch = true
o.autoindent = true
o.cc = '96'
o.ttimeout = true
o.ttimeoutlen = 100
o.ruler = true
o.wildmenu = true
